import { StyleSheet } from 'react-native';
import { light } from './theme';

export const makeStyles = (c: typeof light) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: c.bg },
  authWrap: { flex: 1, width: '100%', maxWidth: 440, alignSelf: 'center', justifyContent: 'center', padding: 20 },
  list: { flex: 1 },
  listContent: { padding: 16, paddingBottom: 48 },
  paneContent: { padding: 16, paddingBottom: 48 },
  gutter: { paddingHorizontal: 16, paddingTop: 8 },
  split: { flex: 1, flexDirection: 'row' },
  side: { width: 320, flexGrow: 0, flexShrink: 0, borderRightWidth: 1, borderRightColor: c.border },
  cardFlat: { borderWidth: 0, padding: 0, backgroundColor: 'transparent' },
  backdrop: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.4)' },
  drawer: { position: 'absolute', top: 0, bottom: 0, left: 0, width: 360, maxWidth: '90%', backgroundColor: c.bg },
  tabs: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: c.border, backgroundColor: c.surface },
  tab: { flex: 1, paddingVertical: 14, alignItems: 'center' },
  tabOn: { borderTopWidth: 2, borderTopColor: c.primary },
  tabTxt: { color: c.muted, fontWeight: '600' },
  tabTxtOn: { color: c.primary },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  logo: { fontSize: 28, fontWeight: '800', color: c.primary },
  tagline: { fontSize: 16, color: c.muted, marginTop: 6, marginBottom: 20, lineHeight: 22 },
  card: { backgroundColor: c.surface, borderRadius: 16, borderWidth: 1, borderColor: c.border, padding: 16, marginBottom: 16 },
  h2: { fontSize: 18, fontWeight: '700', color: c.text, marginBottom: 10 },
  row: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  input: { backgroundColor: c.bg, borderWidth: 1, borderColor: c.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, color: c.text, marginBottom: 10 },
  primaryBtn: { backgroundColor: c.primary, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 4 },
  addBtn: { backgroundColor: c.primary, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 13 },
  primaryTxt: { color: c.onPrimary, fontSize: 16, fontWeight: '700' },
  disabled: { opacity: 0.5 },
  link: { color: c.primary, fontWeight: '600', textAlign: 'center', paddingVertical: 10 },
  error: { color: c.err, marginBottom: 8 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 10 },
  chip: { backgroundColor: c.soft, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 },
  chipTxt: { color: c.primary, fontWeight: '600' },
  quick: { borderWidth: 1, borderColor: c.border, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 },
  quickTxt: { color: c.muted },
  cat: { borderTopWidth: 1, borderTopColor: c.border, paddingTop: 10, marginTop: 10 },
  catHead: { fontSize: 15, fontWeight: '700', color: c.text },
  tog: { backgroundColor: c.bg, borderWidth: 1, borderColor: c.border, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 },
  togOn: { backgroundColor: c.good, borderColor: c.good },
  togTxt: { color: c.text },
  togTxtOn: { color: '#FFFFFF', fontWeight: '600' },
  muted: { color: c.muted, fontSize: 14 },
  resultsHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
  filters: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  filter: { borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8 },
  filterOn: { backgroundColor: c.primary, borderColor: c.primary },
  filterTxt: { color: c.text, fontWeight: '600' },
  filterTxtOn: { color: c.onPrimary },
  recipe: { backgroundColor: c.surface, borderRadius: 16, borderWidth: 1, borderColor: c.border, padding: 14, marginBottom: 10 },
  recipeRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  tile: { width: 52, height: 52, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  tileEmoji: { fontSize: 28 },
  matchLine: { fontSize: 14, fontWeight: '600', marginTop: 2 },
  headline: { fontSize: 28, fontWeight: '300', color: c.text, marginBottom: 8 },
  recipeTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  recipeName: { fontSize: 17, fontWeight: '700', color: c.text, flex: 1 },
  pct: { fontSize: 17, fontWeight: '800', marginLeft: 8 },
  bar: { height: 6, backgroundColor: c.border, borderRadius: 3, marginVertical: 10, overflow: 'hidden' },
  barFill: { height: 6, borderRadius: 3 },
  hint: { color: c.muted, fontSize: 12, marginTop: 6 },
  steps: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: c.border, gap: 6 },
  step: { color: c.text, fontSize: 15, lineHeight: 21 },
  empty: { alignItems: 'center', padding: 32 },
  emptyEmoji: { fontSize: 44 },
  emptyTxt: { color: c.muted, textAlign: 'center', marginTop: 8, fontSize: 15, lineHeight: 22 },
});
